apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "flask.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "flask.name" . }}
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      containers:
        - name: flask
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
{{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
